### PR TITLE
chore: implement browser versions for node-only api methods

### PR DESCRIPTION
**Pull request by stropitek**

### CODE REVIEW

**Comment by stropitek** [comment]
Idea: implement the read function for the browser:

```ts
async function read(dataOrUrl: string | URL | File): Image {
  // If File use FileReader + decode
  // If string or URL use fetch + decode
}
```

Not sure wether it should be 2 separate functions because it could be convenient to have a sync function when having a `File` as input.

**Comment by targos** [comment]
Since `fetch` is also supported in Node.js, I think we should have a different method for it.

**Comment by targos** [comment]
I don't think we can read a `File` synchronously?

**Review by targos — APPROVED** [review]

**Comment by stropitek** [comment]
> I don't think we can read a `File` synchronously?

You are right, I thought that `onload` on `FileReader` was called synchronously

**Pull request merged**
