### PR TITLE
feat: drawCircle

### PR DESCRIPTION
**Pull request by wadjih-bencheikh18**

### CODE REVIEW

**Comment by targos** [comment]
Do you have a reference for the algorithm you used?

**Comment by targos** [comment]
How does it compare to this canvas code for example: https://codesandbox.io/s/canvas-circle-forked-ot7pwh?file=/src/index.js

**Comment by wadjih-bencheikh18** [comment]
> Do you have a reference for the algorithm you used?

No, i made it from scratch. do you want me to add comments ?

**Comment by wadjih-bencheikh18** [comment]
> How does it compare to this canvas code for example: https://codesandbox.io/s/canvas-circle-86vutd?file=/src/index.js

Do you want me to add canvas test to compare the results?

**Comment by lpatiny** [comment]
@wadjih-bencheikh18 In general making this kind of code from scratch may be quite dangerous (source of bug) and not optimized. If a code exists in a licence that is Apache, BSD or MIT we could get strongly inspired and cite them rather than reinventing it.

It is not a problem to reuse code if the licence allows it. In your case I have the impression that the code is not optimized and you could have a look at https://www.cs.helsinki.fi/group/goa/mallinnus/ympyrat/ymp1.html or some existing code.

**Comment by wadjih-bencheikh18** [comment]
@lpatiny i finished implementing drawCircle

**Comment by targos** [comment]
@wadjih-bencheikh18 It's nice that you take care of updating dependencies, but in the future please do it in a separate pull request (unless it's needed for the functionality).

**Pull request merged**
